### PR TITLE
Migrate to Qt6

### PR DESCRIPTION
**Pull request by DorianBDev**
## Description

Migration to Qt6. A lot was already done by @agatti in #16.

## Affected area(s)

- [ ] Core
- [x] GUI
- [ ] Tests

## Changes type

- [ ] Bug fix
- [x] Migration
- [ ] New feature
- [ ] Feature rework 

## Proposed changes

- Patch Degate to migrate to Qt6
- Upgrade CI to support Qt6

### CODE REVIEW

**Comment by DorianBDev** [comment]
Identified issues:
- For the Linux CI, we are missing the `qt6-image-formats-plugins` package, that is not available for Ubuntu 20. Since we need an old Ubuntu to build against an old libc, I don't think moving to Ubuntu 22 (oldest Ubuntu to have a `qt6-image-formats-plugins` package) is a good idea. Trying to backport `qt6-image-formats-plugins` might be a solution.
- A crash is appearing when closing Degate on `WorkspaceRenderer` destructor call. I could only test on Linux, so I don't know if this issue also appears elsewhere.

**Comment by DorianBDev** [comment]
The CI is fixed, deploy jobs should be updated to latest IFW links, otherwise everything should work. Qt6 port should be ready for testing (alpha/beta release)! The last thing is to fix the identified crash on app exit. I'm on it, it's a strange crash, might take some time.

**Comment by agatti** [comment]
> * A crash is appearing when closing Degate on `WorkspaceRenderer` destructor call. I could only test on Linux, so I don't know if this issue also appears elsewhere.

Could it be that `doneCurrent()` is called twice? (both in `WorkspaceRenderer` and in `ImageRenderer`)

**Comment by DorianBDev** [comment]
> > * A crash is appearing when closing Degate on `WorkspaceRenderer` destructor call. I could only test on Linux, so I don't know if this issue also appears elsewhere.
> 
> Could it be that `doneCurrent()` is called twice? (both in `WorkspaceRenderer` and in `ImageRenderer`)

For me it shouldn't have any impact (not the same context?), but it's been a while since I've touched OpenGL... I just tested and modifying this didn't change anything (maybe because when testing for this bug I don't spawn any `ImageRenderer`, so only a `WorkspaceRenderer` exists).

I found another possible source for the bug, in place of `connect(context(), &QOpenGLContext::aboutToBeDestroyed, this, &WorkspaceRenderer::cleanup);` at _WorkspaceRenderer@458_. It has an impact, but I have to dig into to be sure.

**Comment by DorianBDev** [comment]
Another bug I just found: selecting an annotation (or a subproject) make the app crash (it doesn't find the logic layer). I suspect an issue with the project XML loading (here surely a small bug easy to fix).

**Comment by DorianBDev** [comment]
I have fixed all bugs I found, but I only tested the Linux version so there is a high probability that some remains. I'll try to test it on Windows soon, and we'll do more intensive usage. I ran a "deploy" CI for all platforms, this should allow anyone to test the Qt6 port without needing a full rebuild.

Later, I'll merge this and pop a new alpha/beta version of Degate (nightly).

**Comment by agatti** [comment]
For what it's worth, the windows version seems to work fine with the latest Wine on Linux.  Sadly I have no way to test other platforms at this time...

**Comment by DorianBDev** [comment]
I should have fixed all the deployment jobs. I think I'll merge everything in `develop` branch, then merge #12 and pop a new alpha version for testing.

**Pull request merged**
